name: action_process_text
description: A flutter plugin for ACTION_PROCESS_TEXT implementation in android.
version: 1.0.0-nullsafety.0

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.example.action_process_text
        pluginClass: ActionProcessTextPlugin